#!/bin/bash -e

VERSION="0.0.1"

if [ $1 == "version" ]; then
  echo "$VERSION"
  exit 0;
fi

if [ $1 == "help" ]; then
  echo "Usage: dvm [options]"
  echo ""
  echo "Options:"
  echo "  clean:     stop, delete and purge repo vm"
  echo "  ip:        get ip address of repo vm"
  echo "  name:      log name of repo vm"
  echo "  list:      list all developer virtual machines (including those outside repo)"
  echo "  reset:     delete then launch a new fresh intance of the vm"
  echo "  run:       run command inside vm, such as: dvm run npm install"
  echo "  shell:     load bash shell inside the vm"
  echo "  start:     start vm (and if the vm doesn't exist, create it)"
  echo "  stop:      stop vm"
  echo "  version:   log version of dvm cli"
  exit 0;
fi


repo_path=$(git rev-parse --show-toplevel)

# source .dvm if it exists
dot_dvm_path="$repo_path/.dvm"
if [ -f "$dot_dvm_path" ]; then
  echo "dvm: loading .dvm ($dot_dvm_path)"
  source "$dot_dvm_path"
fi

repo_path_hash=$(git rev-parse --show-toplevel | shasum | head -c10)
repo_name=$(basename $repo_path)

# vm names cannot have _ in them
repo_name_slug=$(echo $repo_name | sed s/_/-/g)

if [ -z "$DVM_NAME" ]; then
    vm_name=$(echo "dvm-$repo_name_slug-$repo_path_hash" | sed 's/\./-/')
else
    vm_name=$DVM_NAME
fi

if [ $1 == "name" ]; then
  echo "$vm_name"
  exit 0;
fi

if [ $1 == "list" ]; then
  multipass list | grep $vm_name
  multipass list | grep dvm | grep -v $vm_name
  exit 0;
fi

if multipass info $vm_name > /dev/null 2>&1; then
  vm_exists="true"
  vm_state=$(multipass info --format=yaml $vm_name | grep state | awk '{print $NF}')
else
  vm_exists="false"
  vm_state="na"
fi

launch_or_start_virtual_machine () {
  if [ "$vm_exists" == "true" ]; then
    echo "starting developer virtual machine"
    multipass start $vm_name;
  else
    echo "launching developer virtual machine with name $vm_name"
    multipass launch --name $vm_name --cpus ${DVM_CPUS:-1} --mem ${DVM_MEM:-16GB} --disk ${DVM_DISK:-20G}

    # undo automatic home mount
    multipass unmount $vm_name

    if [ "$DVM_DOCKER" != "false" ]; then
      # add docker key
      multipass exec "$vm_name" -- sh -c 'curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg'

      # set up docker repo
      multipass exec "$vm_name" -- sh -c 'echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null'
    fi

    multipass exec "$vm_name" -- sudo apt-get update

    if [ "$DVM_NODE" != "false" ]; then
      multipass exec "$vm_name" -- sudo apt-get install -y nodejs npm
    fi

    if [ "$DVM_PYTHON" != "false" ]; then
      multipass exec "$vm_name" -- sudo apt-get install -y python python3-pip
      multipass exec "$vm_name" -- pip install pipenv
    fi

    if [ "$DVM_DOCKER" != "false" ]; then
      # install docker-compose v1
      multipass exec "$vm_name" -- sudo apt-get install -y docker-ce docker-ce-cli docker-compose containerd.io

      # install docker compose v2
      multipass exec "$vm_name" -- mkdir -p /home/ubuntu/.docker/cli-plugins/
      multipass exec "$vm_name" -- curl -SL https://github.com/docker/compose/releases/download/v2.3.4/docker-compose-linux-x86_64 -o /home/ubuntu/.docker/cli-plugins/docker-compose
      multipass exec "$vm_name" -- chmod +x /home/ubuntu/.docker/cli-plugins/docker-compose
      multipass exec "$vm_name" -- sudo chown ubuntu /var/run/docker.sock
      multipass exec "$vm_name" -- docker compose version
    fi

    # allow lots of file watching
    multipass exec "$vm_name" -- sudo /bin/su -c "echo 'fs.inotify.max_user_watches=1048576' >> /etc/sysctl.conf && sudo sysctl -p"

    if [ "$DVM_NODE" != "false" ]; then
      # install node packages
      multipass exec "$vm_name" -- sudo npm i -g n np pnpm rollup yarn

      # update to latest node
      multipass exec "$vm_name" -- sudo n latest
    fi

    multipass mount $repo_path "$vm_name:$repo_path"
  fi;
}

if [ $1 == "start" ]; then
  launch_or_start_virtual_machine
  exit 0;
elif [ $1 == "stop" ]; then 
  if [ "$vm_exists" == "true" ]; then
    multipass stop $vm_name
    echo "stopped developer virtual machine"
  fi;
elif [ $1 == "clean" ]; then
  # deletes then purges vm 
  if [ "$vm_exists" == "true" ]; then
    multipass delete -p $vm_name
  fi;
  exit 0;
elif [ $1 == "ip" ]; then
  if [ "$vm_state" == "Running" ]; then
    multipass info --format=yaml $vm_name | grep -A1 ipv4 | tail -n 1 | awk '{print $NF}'
  fi;
elif [ $1 == "reset" ]; then
  if [ "$vm_exists" == "true" ]; then
    multipass delete -p $vm_name
    vm_exists="false"
  fi;
  launch_or_start_virtual_machine
elif [ $1 == "run" ]; then
  launch_or_start_virtual_machine
  statement="${@:2}"
  multipass exec "$vm_name" -- sh -c "cd $PWD && sh -c \"$statement\""
  exit 0;
elif [ $1 == "shell" ]; then
  launch_or_start_virtual_machine
  multipass exec "$vm_name" -- sh -c "cd $PWD && bash"
elif [ $1 == "remount" ]; then
  multipass unmount $vm_name
  multipass mount $repo_path "$vm_name:$repo_path"
else
  echo "dvm: unknown command \"$1\""
  exit 1
fi
